spring:
  application:
    name: consumer-service
  config:
    import: optional:configserver:http://localhost:8888
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    host: 127.0.0.1
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
custom:
  my:
    email:
      from: